# Generated by Django 4.2.23 on 2025-08-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_transaction_id"),
        ("venues", "0002_venue_latitude_venue_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
