# Generated by Django 4.2.23 on 2025-08-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_review_booking_review_updated_at"),
    ]

    operations = []
