# Generated by Django 4.2.23 on 2025-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default-profile.png",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
