# Generated by Django 4.2.23 on 2025-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_amount_paid_booking_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
